name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
# core: 8.x
hidden: true
dependencies:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2018-01-30
version: '8.5.0-alpha1+83-dev'
core: '8.x'
project: 'drupal'
datestamp: 1517310536
